version: '3.7'

services:
  web:
    build: .
    working_dir: /app/project
    command: ["/app/entrypoint.sh", "db", "python -m flask run -h 0.0.0.0"]
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
volumes:
  postgres_data: